# Generated by Django 5.1.5 on 2025-01-28 02:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionfeatureusage',
            name='daily_reset_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionfeatureusage',
            name='daily_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionfeatureusage',
            name='monthly_reset_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionfeatureusage',
            name='monthly_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='subscriptionfeatureusage',
            index=models.Index(fields=['daily_reset_at'], name='core_subscr_daily_r_7b30a8_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionfeatureusage',
            index=models.Index(fields=['monthly_reset_at'], name='core_subscr_monthly_172479_idx'),
        ),
    ]
