# Generated by Django 5.1.5 on 2025-01-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_subscription_usage_tracking_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscriptionfeatureusage',
            name='core_subscr_subscri_84cd4d_idx',
        ),
        migrations.AlterField(
            model_name='subscriptionfeatureusage',
            name='feature_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionfeatureusage',
            name='usage_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
