# Generated by Django 5.1.5 on 2025-01-30 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_communityvote_core_commun_user_id_aa3b83_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('DEVELOPER', 'Developer'), ('DESIGNER', 'Designer'), ('PROJECT_MANAGER', 'Project Manager'), ('QA', 'Quality Assurance'), ('DEVOPS', 'DevOps Engineer'), ('OTHER', 'Other')], max_length=20)),
                ('custom_role', models.CharField(blank=True, help_text="Specify role if 'Other' is selected", max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('github_profile', models.URLField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('contribution_details', models.TextField(help_text="Describe the team member's contributions to the app")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.applisting')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
