# Generated by Django 5.1.5 on 2025-01-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_appteammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appteammember',
            name='role',
            field=models.CharField(choices=[('DEVELOPER', 'Developer'), ('CMO', 'CMO'), ('CEO', 'CEO'), ('QA', 'Quality Assurance'), ('DEVOPS', 'DevOps Engineer'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
