# Generated by Django 5.1.5 on 2025-02-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_appteammember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='cta',
            field=models.CharField(default='Learn More', help_text='Call to action text for the advertisement button', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Max 60 characters for SEO', max_length=100),
        ),
    ]
