# Generated by Django 5.1.5 on 2025-02-03 23:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_advertisement_cta_alter_blog_meta_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='cta',
        ),
        migrations.AddField(
            model_name='applisting',
            name='estimated_development_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated development cost for nominated apps, set by admin after research', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='applisting',
            name='funding_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Funding goal for listed apps. For nominated apps, this will be set by admin after research.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
