# Generated by Django 5.1.5 on 2025-02-04 06:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_advertisement_cta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applisting',
            name='estimated_development_cost',
        ),
        migrations.AddField(
            model_name='applisting',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this app has been viewed'),
        ),
        migrations.AlterField(
            model_name='applisting',
            name='funding_goal',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
