# Generated by Django 5.1.5 on 2025-02-04 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_applisting_estimated_development_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcomment',
            name='is_system_generated',
            field=models.BooleanField(default=False, help_text='Whether this comment was generated by the system'),
        ),
        migrations.AddField(
            model_name='communityvote',
            name='is_system_generated',
            field=models.BooleanField(default=False, help_text='Whether this vote was generated by the system'),
        ),
        migrations.CreateModel(
            name='EngagementAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_added', models.PositiveIntegerField(default=0)),
                ('likes_added', models.PositiveIntegerField(default=0)),
                ('upvotes_added', models.PositiveIntegerField(default=0)),
                ('comments_added', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(help_text='Reason for the adjustment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_adjustments', to=settings.AUTH_USER_MODEL)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_adjustments', to='core.applisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app', '-created_at'], name='core_engage_app_id_432f82_idx'), models.Index(fields=['admin', '-created_at'], name='core_engage_admin_i_c087ae_idx')],
            },
        ),
    ]
