# Generated by Django 5.1.5 on 2025-02-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_appcomment_is_system_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applisting',
            name='system_like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applisting',
            name='system_upvote_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
