# Generated by Django 5.1.5 on 2025-02-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_applisting_system_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applisting',
            name='system_like_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of system-generated likes'),
        ),
        migrations.AlterField(
            model_name='applisting',
            name='system_upvote_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of system-generated upvotes'),
        ),
    ]
