# Generated by Django 5.1.5 on 2025-02-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_applisting_system_like_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applisting',
            name='system_comment_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of system-generated comments'),
        ),
    ]
