# Generated by Django 5.1.5 on 2025-02-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_applisting_system_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='applisting',
            name='nomination_external_link',
            field=models.URLField(blank=True, help_text='External link (e.g., YouTube video) for the nominated app', null=True),
        ),
    ]
