# Generated by Django 5.1.5 on 2025-02-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_applisting_nomination_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='applisting',
            name='last_trending_update',
            field=models.DateTimeField(blank=True, help_text='When the trending status was last updated', null=True),
        ),
        migrations.AddField(
            model_name='applisting',
            name='manual_trending',
            field=models.BooleanField(default=False, help_text='Manual override for trending status set by admin'),
        ),
    ]
