# Generated by Django 5.1.5 on 2025-02-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_applisting_last_trending_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backup Management',
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
    ]
