# Generated by Django 5.1.5 on 2025-02-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_transaction_core_transa_user_id_257e65_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applisting',
            name='deployment_type',
            field=models.CharField(blank=True, choices=[('SAAS', 'Software as a Service'), ('SELF_HOSTED', 'Self Hosted'), ('MOBILE_APP', 'Mobile App'), ('DESKTOP_APP', 'Desktop App'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applisting',
            name='monthly_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current monthly revenue of the app', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='applisting',
            name='monthly_users',
            field=models.PositiveIntegerField(blank=True, help_text='Current monthly active users', null=True),
        ),
        migrations.AddField(
            model_name='applisting',
            name='sale_includes_assets',
            field=models.BooleanField(default=True, help_text='Whether the sale includes all assets (images, designs, etc.)'),
        ),
        migrations.AddField(
            model_name='applisting',
            name='sale_includes_source_code',
            field=models.BooleanField(default=True, help_text='Whether the sale includes full source code'),
        ),
        migrations.AddField(
            model_name='applisting',
            name='sale_includes_support',
            field=models.BooleanField(default=False, help_text='Whether post-sale technical support is included'),
        ),
        migrations.AddField(
            model_name='applisting',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed price for outright purchase of the app', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='applisting',
            name='support_duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of included technical support in months', null=True),
        ),
        migrations.AddField(
            model_name='applisting',
            name='tech_stack',
            field=models.JSONField(blank=True, default=dict, help_text='Technologies and frameworks used in the app'),
        ),
        migrations.AlterField(
            model_name='applisting',
            name='listing_type',
            field=models.CharField(choices=[('LISTED', 'Listed'), ('NOMINATED', 'Nominated'), ('COMMUNITY', 'Community Suggested'), ('FOR_SALE', 'For Sale')], default='LISTED', help_text='Whether this is a listed app by developer or a community nominated app', max_length=20),
        ),
    ]
