# Generated by Django 5.1.5 on 2025-02-10 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_applisting_deployment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.applisting')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app', '-created_at'], name='core_appmes_app_id_37eab6_idx'), models.Index(fields=['sender', '-created_at'], name='core_appmes_sender__e5a638_idx'), models.Index(fields=['recipient', '-created_at'], name='core_appmes_recipie_e6b493_idx')],
            },
        ),
    ]
