# Generated by Django 5.1.5 on 2025-02-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_appmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmessage',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether the message has been archived'),
        ),
    ]
