# Generated by Django 5.1.4 on 2025-02-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_notification_severity_alter_notification_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INVESTMENT', 'Investment Update'), ('PRICE', 'Price Alert'), ('SYSTEM', 'System Notification'), ('SYSTEM_ERROR', 'System Error'), ('MILESTONE', 'Portfolio Milestone'), ('APP_UPDATE', 'App Update'), ('FUNDING_GOAL', 'Funding Goal Reached'), ('DIVIDEND', 'Dividend Payment'), ('SECURITY', 'Security Alert'), ('MAINTENANCE', 'System Maintenance'), ('NEWS', 'App News'), ('APP_APPROVAL', 'App Approval Status'), ('PAYMENT_PENDING', 'Payment Processing'), ('FUNDING_COMPLETE', 'Funding Complete')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('INVESTMENT', 'Investment Update'), ('PRICE', 'Price Alert'), ('SYSTEM', 'System Notification'), ('SYSTEM_ERROR', 'System Error'), ('MILESTONE', 'Portfolio Milestone'), ('APP_UPDATE', 'App Update'), ('FUNDING_GOAL', 'Funding Goal Reached'), ('DIVIDEND', 'Dividend Payment'), ('SECURITY', 'Security Alert'), ('MAINTENANCE', 'System Maintenance'), ('NEWS', 'App News'), ('APP_APPROVAL', 'App Approval Status'), ('PAYMENT_PENDING', 'Payment Processing'), ('FUNDING_COMPLETE', 'Funding Complete')], max_length=20),
        ),
    ]
